#!/usr/bin/env bash
# Generate the secret-bearing SIP config from asterisk/roster.csv.
#
# One password per extension is written to BOTH places that must agree:
#   - asterisk/config/asterisk/custom/pjsip_custom.conf   (Asterisk endpoints)
#   - asterisk/sip-core-options.yaml                      (paste into HA: SIP Core -> Configure)
# plus the AMI password in asterisk/config/config.json.
# All three are gitignored. Re-running rotates every password, so it refuses to
# overwrite unless FORCE=1.
set -euo pipefail
cd "$(dirname "$0")"

# The public name Caddy serves (SITE_HOST in ../.env). Browsers reach Asterisk's
# /ws through it, so it must match the TLS certificate.
SIP_HOST="${SIP_HOST:-$(sed -n 's/^SITE_HOST=//p' ../.env)}"
[[ -n $SIP_HOST ]] || { echo "Set SITE_HOST in .env first." >&2; exit 1; }

PJSIP=config/asterisk/custom/pjsip_custom.conf
OPTS=sip-core-options.yaml
AMI=config/config.json

if [[ -e $PJSIP && ${FORCE:-0} != 1 ]]; then
    echo "$PJSIP exists; re-run with FORCE=1 to rotate all passwords." >&2
    exit 1
fi
mkdir -p "$(dirname "$PJSIP")"

pw() { openssl rand -base64 24 | tr -d '/+=\n' | cut -c1-24; }

umask 077
printf '{\n  "ami_password": "%s",\n  "auto_add": false,\n  "generate_ssl_cert": true\n}\n' "$(pw)" > "$AMI"

# Endpoint templates: what the add-on's auto_add would have defined, which we
# replicate because auto_add is off (see roster.csv). webrtc=yes turns on
# DTLS-SRTP/ICE/rtcp-mux, which browsers require.
cat > "$PJSIP" <<'EOF'
; GENERATED by asterisk/generate-secrets.sh from asterisk/roster.csv. Do not edit; do not commit.

[sipjs-phone-auth](!)
type=auth
auth_type=userpass

[sipjs-phone-aor](!)
type=aor
max_contacts=6
remove_existing=yes
remove_unavailable=yes
qualify_frequency=0

[sipjs-phone-endpoint](!)
type=endpoint
send_rpid=yes
send_pai=yes
device_state_busy_at=1
webrtc=yes
from_domain=asterisk
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
context=default
disallow=all
allow=opus,ulaw,alaw,g722
EOF

cat > "$OPTS" <<EOF
# GENERATED by asterisk/generate-secrets.sh. Paste into:
#   HA -> Settings -> Devices & services -> SIP Core -> Configure
# Not supervised, so there is no ingress: Caddy terminates TLS on 443 and
# proxies /ws to Asterisk, so the URL is given directly. wss:// works from both
# https pages (the HA app, Fully Kiosk) and the old http pages.
custom_wss_url: wss://${SIP_HOST}/ws
ice_config:
  iceGatheringTimeout: 1000
  iceCandidatePoolSize: 0
  iceTransportPolicy: all
  iceServers: []   # LAN only: no STUN, so no Google dependency
  rtcpMuxPolicy: require
outgoingRingtoneUrl: /sip_core_files/ringback-tone.mp3
incomingRingtoneUrl: /sip_core_files/ring-tone.mp3
sip_video: false
auto_answer: false
EOF

users="" contacts="" backup=""
while IFS=, read -r ext name haid; do
    [[ -z $ext || $ext == \#* ]] && continue
    p=$(pw)
    cat >> "$PJSIP" <<EOF

[$ext](sipjs-phone-aor)
[$ext](sipjs-phone-auth)
username=$ext
password=$p
[$ext](sipjs-phone-endpoint)
aors=$ext
auth=$ext
callerid="$name" <$ext>
EOF
    contacts+="    \"$ext\":"$'\n'"      name: \"$name\""$'\n'
    if [[ -n $haid ]]; then
        users+="  # $name"$'\n'"  - ha_username: \"$haid\""$'\n'"    extension: \"$ext\""$'\n'"    password: \"$p\""$'\n'
    else
        backup="backup_user:"$'\n'"  ha_username: guest"$'\n'"  extension: \"$ext\""$'\n'"  password: \"$p\""$'\n'
    fi
done < roster.csv

{
    printf '%s' "$backup"
    printf 'users:\n%s' "$users"
    printf 'popup_config:\n  auto_open: true\n  large: false\n  hide_header_button: false\n  buttons: []\n  extensions:\n%s' "$contacts"
} >> "$OPTS"

echo "wrote $PJSIP, $OPTS, $AMI (WebSocket host: $SIP_HOST)"
